[profile.default]
ffi = true
ast = true
build_info = true
src = "contracts"
out = "out"
extra_output = ["storageLayout"]
libs = ["lib"]
solc = "0.8.30"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./"}]
evm_version = "cancun"
[rpc_endpoints]
fraxtalMainnet = "https://rpc.frax.com"
fraxtalTestnet = "https://rpc.testnet.frax.com"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options